/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:235d20b7-b31e-4e56-be78-bf89f18e3e73",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ooFJljxdL",
    "aws_user_pools_web_client_id": "3j0b8l7fo4mrtsf88qqa7gl272",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://777f6ecfivh73nhjl6lpeknfuy.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b54trzibwbhmjm4gnee7ukusse"
};


export default awsmobile;
