/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:1e487640-0d60-4e3d-9504-d550176a65b3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_RgNCXB1LE",
    "aws_user_pools_web_client_id": "7tb31qremv5385hsifdd3ao9k8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "http://192.168.1.23:20002/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true
};


export default awsmobile;
